name: Cookies-Vision-Modpack

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install zip
        run: sudo apt-get install zip -y
      
      - name: Create test zip
        run: |
          echo '{ "namespace": "GreenTF", "name": "test", "description": "Test", "version_number": "1.${{ github.run_number }}.0", "dependencies": [], "website_url": "https://greenboi.me" }' > manifest.json
          zip -r test.zip .
      
      - name: Publish to Thunderstore
        uses: GreenTF/upload-thunderstore-package@v4.2
        with:
          namespace: ChocolateCookies # Update with your desired namespace
          description: A Lethal Company VanillaPlus experience that aims to enhance the gameplay loop of LC.
          token: ${{ secrets.COOKIESSERVICE }}
          name: Cookies Vision Modpack # Update with your desired package name
          version: 1.${{ github.run_number }}.0 # Update versioning as needed
          community: lethal-company
          repo: thunderstore.io/c/lethal-company
          categories: |
            modpacks
            monsters
            emotes
          file: ./test.zip

      - name: Display Thunderstore URL
        run: echo ${{ steps['Publish to Thunderstore'].outputs.url }}
