<<<<<<< HEAD
name: Test Action

on:
  push:
=======
name: Cookies-Vision-Modpack

on:
  push:
    branches:
      - main
>>>>>>> 216e645c4c117f68fc93df0dafdac506c3950e62
  pull_request:
    branches:
      - main
  workflow_dispatch:
<<<<<<< HEAD
  


jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - id: pub
        uses: ./
        with:
          namespace: ChocolateCookies
          name: Cookies Vision Modpack
          token: ${{ secrets.TS_KEY }}
          description: |
            The FitnessGram Pacer test is a multistage aerobic capacity test that progressively gets more difficult as it continues. 
            The 20 meter Pacer test will begin in 30 seconds. 
            Line up at the start. The running speed starts slowly, but gets faster each minute after you hear this signal *boop*.
            A single lap should be completed each time you hear this sound *ding*. Remember to run in a straight line, and run as long as possible. 
            The second time you fail to complete a lap before the sound, your test is over. The test will begin on the word start. 
            On your mark, get ready, start.
          version: v0.${{ github.run_number }}.0
          community: lethal-company
          repo: thunderstore.io
          wrap: modpacks
          website: "https://greenboi.me"
          categories: |
            modpacks
            emotes
            suits
            equipment
            items
            monsters
            furniture
            tools
            audio
          deps: |
            GreenTF-test@2708437257.35.1
      - run: echo ${{ steps.pub.outputs.url }}
          
      
      

  # publish:
  #   needs: test
  #   if: github.event_name == 'push'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Create Release
  #       uses: marvinpinto/action-automatic-releases@latest
  #       with:
  #         repo_token: ${{ secrets.GITHUB_TOKEN }}
  #         prelease: false






        
=======

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install zip
        run: sudo apt-get install zip -y
      
      - name: Create test zip
        run: |
          echo '{ "namespace": "GreenTF", "name": "test", "description": "Test", "version_number": "1.${{ github.run_number }}.0", "dependencies": [], "website_url": "https://greenboi.me" }' > manifest.json
          zip -r test.zip .
      
      - name: Publish to Thunderstore
        uses: GreenTF/upload-thunderstore-package@v4.2
        with:
          namespace: ChocolateCookies # Update with your desired namespace
          description: A Lethal Company VanillaPlus experience that aims to enhance the gameplay loop of LC.
          token: ${{ secrets.COOKIESSERVICE }}
          name: Cookies Vision Modpack # Update with your desired package name
          version: 1.${{ github.run_number }}.0 # Update versioning as needed
          community: lethal-company
          repo: thunderstore.io/c/lethal-company
          categories: |
            modpacks
            monsters
            emotes
          file: ./test.zip

      - name: Display Thunderstore URL
        run: echo ${{ steps['Publish to Thunderstore'].outputs.url }}
>>>>>>> 216e645c4c117f68fc93df0dafdac506c3950e62
