name: Cookies-Vision-Modpack

# Run when a new release is... released
on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
  
    runs-on: ubuntu-latest
    
    steps:
      # Use checkout to publish the files in your repo
      - uses: actions/checkout@v3
      - name: create test zip
        run: |
          sudo apt install zip
          echo "{ \"namespace\": \"GreenTF\", \"name\": \"test\", \"description\": \"Test\", \"version_number\": \"1.${{ github.run_number }}.0\",  \"dependencies\": [], \"website_url\": \"https://greenboi.me\" }" >> manifest.json
          zip test.zip ./*
      - id: pub
        uses: ./
        with:
          namespace: ChocolateCookies # the thunderstore 'team' to publish under
          description: A Lethal Company VanillaPlus experience that aims to enhance the gameplay loop of LC.
          token: ${{ secrets.COOKIESSERVICE }}
          name: Cookies Vision Modpack # the name of the package
          version: ${{ github.ref_name }} # Use the tag as the package version
          community: lethal=company
          repo: thunderstore.io/c/lethal-company
          categories: | # <-- notice this pipe character
            modpacks
            monsters
            emotes
          file: ./test.zip
      - run: echo ${{ steps.pub.outputs.url }}
