name: Upload Prebuilt Zip (Cosmetics)

on:
  push:
    paths:
      - 'CookiesCOSMETICS/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  handleCosmetic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create CookiesCOSMETICS Zip
        run: |
          sudo apt-get install zip
          cd CookiesCOSMETICS
          zip -r ../CookiesCOSMETICS.zip icon.png manifest.json README.md CHANGELOG.md
      - id: pub
        uses: ./
        with:
          namespace: ChocolateCookies
          name: CookiesCOSMETICS
          token: ${{ secrets.TS_KEY }}
          description: |
            A component focusing on cosmetic enhancements for Cookies Vision Modpack, please do not download independently.
          version: v1.${{ github.run_number }}.0
          community: lethal-company
          repo: thunderstore.io
          website: "https://creampies.wtf"
          categories: |
            asset-replacements
            emotes
            furniture
            monsters
            items
            equipment
            suits
            tools
            mods
            modpacks
            misc
            audio
            bepinex
          # Check the correct format for dependencies in Thunderstore
          deps: |
            ChocolateCookies-CookiesCOSMETICS-1.${{ github.run_number }}.0
          file: ./CookiesCOSMETICS.zip
      - run: echo ${{ steps.pub.outputs.url }}
