name: Upload Modpack

on:
  push:
    paths:
      - 'CHANGELOG.md'
  workflow_dispatch:



jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - id: pub
        uses: ./
        with:
          namespace: ChocolateCookies
          name: Cookies Vision Modpack
          token: ${{ secrets.TS_KEY }}
          description: |
            A Lethal Company VanillaPlus experience that aims to enhance the gameplay loop of LC.
          version: v0.${{ github.run_number }}.0
          community: lethal-company
          repo: thunderstore.io
#          wrap: modpacks
          website: "https://creampies.wtf"
          categories: |
            asset-replacements
            emotes
            furniture
            monsters
            items
            equipment
            suits
            tools
            mods
            modpacks
            misc
            audio
            bepinex
      - run: echo ${{ steps.pub.outputs.url }}

        # publish:
        #   needs: test
        #   if: github.event_name == 'push'
        #   runs-on: ubuntu-latest
        #   steps:
        #     - name: Create Release
        #       uses: marvinpinto/action-automatic-releases@latest
        #       with:
        #         repo_token: ${{ secrets.GITHUB_TOKEN }}
        #         prelease: false



