name: Create CVUtilities Zip

on:
  push:
    paths:
      - 'CookiesVisionModpack/CVUtilities/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create CVUtilities Zip
        working-directory: CookiesVisionModpack/CVUtilities
        run: |
          zip -r ../../CVUtilities.zip CookiesVisionUtilities.dll icon.png manifest.json README.md

      - name: Upload CVUtilities Zip
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: CVUtilities
          path: ./CVUtilities.zip
