name: Auto Upload to Thunderstore

on:
  push:
    paths:
      - 'CHANGELOG.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest version from CHANGELOG
        id: get_version
        run: |
          latest_version=$(grep -oP '^#\sCookies Vision \K\d+\.\d+\.\d+' CHANGELOG.md | head -1)
          echo "Latest version: $latest_version"
          echo "::set-output name=version::$latest_version"

      - name: Create modpack zip
        run: |
          mkdir -p temp/CookiesVisionModpack
          cp icon.png manifest.json README.md temp/CookiesVisionModpack/
          # Add BepInEx folder or other necessary files/directories to temp/CookiesVisionModpack/ as needed
          zip -r CookiesVisionModpack-${{ steps.get_version.outputs.version }}.zip temp/CookiesVisionModpack/*

      - name: Publish to Thunderstore
        if: success()
        uses: GreenTF/upload-thunderstore-package@v4.2
        with:
          namespace: ChocolateCookies
          description: Your modpack description
          token: ${{ secrets.THUNDERSTORE_TOKEN }}
          name: Cookies Vision Modpack
          version: ${{ steps.get_version.outputs.version }}
          community: lethal-company
          file: ./CookiesVisionModpack-${{ steps.get_version.outputs.version }}.zip
          categories: |
            modpacks
            monsters
            emotes

      - name: Remove modpack zip from repo
        if: success()
        run: |
          rm -f CookiesVisionModpack-${{ steps.get_version.outputs.version }}.zip