name: Upload Prebuilt Zip (Util)

on:
  push:
    paths:
      - 'CVUtilities/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create CVUtilities Zip
        run: |
          sudo apt install zip
          cd CVUtilities
          zip -r ../CVUtilities.zip .

      - name: Upload CVUtilities Zip
        uses: thunderstore/actions/upload@v1
        with:
          apiKey: ${{ secrets.THUNDERSTORE_API_KEY }}
          file: ./CVUtilities.zip
