name: Upload Prebuilt Zip (Utilities)

on:
  push:
    paths:
      - 'CookiesVisionModpack/CVUtilities/manifest.json'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  upload_to_thunderstore:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Create CVUtilities Zip
        run: |
          sudo apt install zip
          zip -r CVUtilities.zip CookiesVisionModpack/CVUtilities/CookiesVisionUtilities.dll CookiesVisionModpack/CVUtilities/icon.png CookiesVisionModpack/CVUtilities/manifest.json CookiesVisionModpack/CVUtilities/README.md
      
      - name: Upload to Thunderstore
        id: upload
        uses: thunderstore-io/github-action@v1
        with:
          namespace: ChocolateCookies
          name: CVUtilities
          token: ${{ secrets.TS_KEY }}
          description: |
            Some patches for the Cookie's Vision Modpack, please do not download independently.
          version: v1.${{ github.run_number }}.0
          community: lethal-company
          repo: thunderstore.io
          website: "https://creampies.wtf"
          categories: |
            asset-replacements
            emotes
            furniture
            monsters
            items
            equipment
            suits
            tools
            mods
            libraries
            misc
            audio
            bepinex
          deps: |
            ChocolateCookies-CVUtilities-1.${{ github.run_number }}.0
          file: ./CVUtilities.zip
      
      - name: Display Thunderstore URL
        run: echo ${{ steps.upload.outputs.url }}
