name: Upload Prebuilt Zip (Utilities)

on:
  push:
    paths:
      - 'CVUtilities/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create CVUtilities Zip
        run: |
          sudo apt-get install zip
          cd CVUtilities
          zip -r ../Cookies_Vision_Utilities.zip CookiesVisionUtilities.dll icon.png manifest.json README.md 
      - id: pub
        uses: ./
        with:
          namespace: ChocolateCookies
          name: Cookies Vision Utilities
          token: ${{ secrets.TS_KEY }}
          description: |
            Some patches for the Cookie's Vision Modpack.
          version: v1.${{ github.run_number }}.0
          community: lethal-company
          repo: thunderstore.io
          website: "https://creampies.wtf"
          categories: |
            asset-replacements
            emotes
            furniture
            monsters
            items
            equipment
            suits
            tools
            mods
            misc
            audio
            bepinex
          # Check the correct format for dependencies in Thunderstore
          deps: | 
            ChocolateCookies-Cookies_Vision_Utilities-1.${{ github.run_number }}.0
          file: ./Cookies_Vision_Utilities.zip
      - run: echo ${{ steps.pub.outputs.url }}
