name: Upload Prebuilt Zip (Moons/Dungeons)

on:
  push:
    paths:
      - 'CookiesMOONS/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  handleMoons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create CookiesMOONS Zip
        run: |
          sudo apt-get install zip
          cd CookiesMOONS
          zip -r ../CookiesMOONS.zip icon.png manifest.json BepInEx README.md CHANGELOG.md
      - id: pub
        uses: ./
        with:
          namespace: ChocolateCookies
          name: CookiesMOONS
          token: ${{ secrets.TS_KEY }}
          description: |
            A Moons & Dungeons component for Cookies Vision Modpack, please do not download independently!
          version: v1.${{ github.run_number }}.0
          community: lethal-company
          repo: thunderstore.io
          website: "https://creampies.wtf"
          categories: |
            asset-replacements
            emotes
            furniture
            monsters
            items
            equipment
            suits
            tools
            mods
            modpacks
            misc
            audio
            bepinex
          # Check the correct format for dependencies in Thunderstore
          deps: |
            ChocolateCookies-CookiesMOONS-1.${{ github.run_number }}.0
          file: ./CookiesMOONS.zip
      - run: echo ${{ steps.pub.outputs.url }}
